#line 1 "../main.c"
#include <Arduino.h>
#line 1
/* Main.ino file generated by New Project wizard
 *
 * Created:   Tue Jul 7 2026
 * Processor: Arduino Uno
 * Compiler:  Arduino AVR (Proteus)
 */

// Peripheral Configuration Code (do not edit)
//---CONFIG_BEGIN---
#pragma GCC push_options
#pragma GCC optimize ("Os")

#include <core.h> // Required by cpu
#include <cpu.h>

#pragma GCC pop_options

// Peripheral Constructors
CPU &cpu = Cpu;

void peripheral_setup () {
}

void peripheral_loop() {
}
//---CONFIG_END---


/* Includes */
#include <avr/io.h>
#include <avr/interrupt.h>
#include "StdTypes.h"

/* BSW & MCAL APIs */
#include "EcuM.h"
#include "IoHwAb.h"
#include "DemSf.h"
#include "ComSf.h"
#include "DcmSf.h"
#include "AdcSf.h"
#include "GptSf.h"

/* ASW Runnable APIs */
#include "SWC_SensorMeasurement.h"
#include "SWC_PidController.h"
void peripheral_setup ();
void peripheral_loop ();
void App_Task_10ms (void );
void App_Task_50ms (void );
void App_Task_100ms (void );
void App_Task_500ms (void );
int main (void );
#line 46

/* =====================================================================
 * AUTOSAR TASK DEFINITIONS
 * ===================================================================== */

/* Task 10ms: Control Loop & Data Acquisition*/
void App_Task_10ms(void)
{
	EcuM_StateType st = EcuM_GetState();
	if ((st == ECUM_STATE_RUN) || (st == ECUM_STATE_PRE_SLEEP))
	{
		/* 1. INPUT (BSW): Process raw hardware data, filter, and publish to RTE */
		IoHwAb_Sensor_MainFunction();
	}
	if (st == ECUM_STATE_RUN) 
	{
		/* 2. DIAGNOSTICS (BSW): Evaluate electrical errors and update debounce counters */
		DemSf_MainFunction();

		/* 3. LOGIC (ASW): Extract physical values from RTE and run PID control */
		SWC_SensorMeasurement_Runnable(); 
		
		float v_in = SWC_SensorMeasurement_GetVin();
		float v_out = SWC_SensorMeasurement_GetVout();
		
		SWC_PidController_Runnable(v_in, v_out);

		/* 4. OUTPUT (BSW): Fetch logical commands from RTE and apply to PWM/DIO drivers */
		IoHwAb_Actuator_MainFunction();
	}

	/* 5. EcuM Main Function */
	EcuM_MainFunction(); 

}

/* Task 50ms: UDS Parser & Cyclic Telemetry Transmission*/
void App_Task_50ms(void)
{
	/* 1. Monitor KL15 status */
	IoHwAb_Kl15_MainFunction();

    /* 2. Rx (BSW): Parse incoming UDS diagnostic frames from tester */
    Com_MainFunction_Rx();

	EcuM_StateType st = EcuM_GetState();
    if ((st == ECUM_STATE_RUN) || (st == ECUM_STATE_PRE_SLEEP))
	{
		/* 3. Tx (BSW): Transmit cyclic diagnostic frames and system telemetry*/
		Com_MainFunction_Tx();
	}

}

/* Task 100ms: Adc_StartScan cycle*/
void App_Task_100ms(void)
{
	EcuM_StateType st = EcuM_GetState();
	if ((st == ECUM_STATE_RUN) || (st == ECUM_STATE_PRE_SLEEP))
	{
		/* TRIGGER: Trigger next ADC scan cycle*/
		Adc_StartScan();
		/* TRIGGER: Trigger next tank level scan cycle*/
		IoHwAb_Level_MainFunction();
	}
}

/* Task 500ms: Diagnostic Test Routines */
void App_Task_500ms(void)
{
    /* 1. ASW: Execute active UDS 0x31 diagnostic test routines */
    //SWC_RoutineCtrl_Runnable_500ms();

}

/* =====================================================================
 * MAIN EXECUTION
 * ===================================================================== */
int main(void)
{
    /* 1. Initialize ECU state, hardware drivers, and BSW services */
    EcuM_Init();

    /* 2. Enable global interrupts*/
    sei();

    /* 3. OS Scheduler Dispatcher Loop*/
    while (1) 
    {
        if (g_flag_task_10ms) 
        {
            g_flag_task_10ms = 0U;
            App_Task_10ms();
        }

        if (g_flag_task_50ms) 
        {
            g_flag_task_50ms = 0U;
            App_Task_50ms();
        }

        if (g_flag_task_100ms) 
        {
            g_flag_task_100ms = 0U;
            App_Task_100ms();
        }

        if (g_flag_task_500ms) 
        {
            g_flag_task_500ms = 0U;
            App_Task_500ms();
        }
    }
    
    return 0;
}