/* Main.ino file generated by New Project wizard
 *
 * Created:   Tue Jul 7 2026
 * Processor: Arduino Uno
 * Compiler:  Arduino AVR (Proteus)
 */

// Peripheral Configuration Code (do not edit)
//---CONFIG_BEGIN---
#pragma GCC push_options
#pragma GCC optimize ("Os")

#include <core.h> // Required by cpu
#include <cpu.h>

#pragma GCC pop_options

// Peripheral Constructors
CPU &cpu = Cpu;

void peripheral_setup () {
}

void peripheral_loop() {
}
//---CONFIG_END---

/* Forward declaration - must come first so Arduino's auto-generated
   prototypes (inserted right after includes) can reference this type
   before the full struct definition appears later in the file. */ 
typedef struct PID_Controller PID_Controller;
typedef struct DTC_StatusType DTC_StatusType;   
typedef struct Dem_ConfigType Dem_ConfigType;

/* Includes */
#include <avr/io.h>
#include <avr/interrupt.h>

#include "Rte.h"
#include "BSW_MCAL.h"

#define TRUE 1U
#define FALSE 0U

/* Variabile Globale pentru Tensiuni (folosite în Task 10ms ?i Rutine) */
static float V_in = 0.0f;
static float V_out = 0.0f;

/* ================= DEM SF ========================= */

/* Starile posibile ale unui DTC conform standardelor auto */
#define DEM_STATUS_OK        0U  
#define DEM_STATUS_PENDING   1U  
#define DEM_STATUS_CONFIRMED 2U  

#define DTC_STATUS_MISSING 0U
#define DTC_STATUS_PASSIVE 1U
#define DTC_STATUS_ACTIVE  2U

/* Pragul de debouncing */
#define DEBOUNCE_THRESHOLD   100U

/* Electrical error type */
#define SHORT_TO_VBAT        1U
#define SHORT_TO_GND         2U
#define OPEN_CIRCUIT_VOLTAGE 3U
#define OPEN_CIRCUIT_CURRENT 4U

/* Structura DTC_StatusType actualizata */
struct DTC_StatusType {
    uint32_t dtc_code;          
    uint8_t  qualifying_status;   
    uint8_t  fault_status;      // 0 = Missing/Empty, 1 = Passive, 2 = Active         
    uint8_t  debounce_cnt;      
    uint16_t freeze_frame_data; 
    volatile uint16_t *adc_source_ptr;
    uint8_t (*monitor_func)(uint16_t raw, uint8_t mode); 
	uint8_t  error_mode;        // Modul de eroare stocat in structura
};

/* Functia de monitorizare a erorilor electrice */
uint8_t DemSf_Monitor_ElectricalFaults(uint16_t raw, uint8_t mode)
{
	if (mode == SHORT_TO_GND)
	{
		if (raw == 0) return 1;
	}
	else if (mode == SHORT_TO_VBAT)
	{
		if (raw == 1023) return 1; 
	}
	else if (mode == OPEN_CIRCUIT_VOLTAGE)
	{
		if (raw > 810 && raw != 1023) return 1; 
	}
	else if (mode == OPEN_CIRCUIT_CURRENT)
	{
		if (raw < 400 && raw != 0) return 1; 
	}
    return 0; 
}

/* Definitia tabelului unificat */
DTC_StatusType g_dtc_table[] = {
    { 0x1A0100, DEM_STATUS_OK, DTC_STATUS_MISSING, 0, 0, &g_adc_raw[0], DemSf_Monitor_ElectricalFaults, SHORT_TO_VBAT}, // Iin_SHORT_TO_VBAT
    { 0x1A0101, DEM_STATUS_OK, DTC_STATUS_MISSING, 0, 0, &g_adc_raw[1], DemSf_Monitor_ElectricalFaults, SHORT_TO_VBAT}, // Vin_SHORT_TO_VBAT
    { 0x1A0102, DEM_STATUS_OK, DTC_STATUS_MISSING, 0, 0, &g_adc_raw[2], DemSf_Monitor_ElectricalFaults, SHORT_TO_VBAT}, // Iout_SHORT_TO_VBAT
    { 0x1A0103, DEM_STATUS_OK, DTC_STATUS_MISSING, 0, 0, &g_adc_raw[3], DemSf_Monitor_ElectricalFaults, SHORT_TO_VBAT}, // Vout_SHORT_TO_VBAT
	{ 0x1A0110, DEM_STATUS_OK, DTC_STATUS_MISSING, 0, 0, &g_adc_raw[0], DemSf_Monitor_ElectricalFaults, SHORT_TO_GND}, // Iin_SHORT_TO_GND
    { 0x1A0111, DEM_STATUS_OK, DTC_STATUS_MISSING, 0, 0, &g_adc_raw[1], DemSf_Monitor_ElectricalFaults, SHORT_TO_GND}, // Vin_SHORT_TO_GND
    { 0x1A0112, DEM_STATUS_OK, DTC_STATUS_MISSING, 0, 0, &g_adc_raw[2], DemSf_Monitor_ElectricalFaults, SHORT_TO_GND}, // Iout_SHORT_TO_GND
    { 0x1A0113, DEM_STATUS_OK, DTC_STATUS_MISSING, 0, 0, &g_adc_raw[3], DemSf_Monitor_ElectricalFaults, SHORT_TO_GND}, // Vout_SHORT_TO_GND
	{ 0x1A0120, DEM_STATUS_OK, DTC_STATUS_MISSING, 0, 0, &g_adc_raw[0], DemSf_Monitor_ElectricalFaults, OPEN_CIRCUIT_CURRENT}, // Iin_OPEN_CIRCUIT
    { 0x1A0121, DEM_STATUS_OK, DTC_STATUS_MISSING, 0, 0, &g_adc_raw[1], DemSf_Monitor_ElectricalFaults, OPEN_CIRCUIT_VOLTAGE}, // Vin_OPEN_CIRCUIT
    { 0x1A0122, DEM_STATUS_OK, DTC_STATUS_MISSING, 0, 0, &g_adc_raw[2], DemSf_Monitor_ElectricalFaults, OPEN_CIRCUIT_CURRENT}, // Iout_OPEN_CIRCUIT
    { 0x1A0123, DEM_STATUS_OK, DTC_STATUS_MISSING, 0, 0, &g_adc_raw[3], DemSf_Monitor_ElectricalFaults, OPEN_CIRCUIT_VOLTAGE}, // Vout_OPEN_CIRCUIT
};

#define TOTAL_DTCS (sizeof(g_dtc_table) / sizeof(g_dtc_table[0]))

void Dem_UpdateEvent(DTC_StatusType *dtc, uint8_t error_condition)
{
    if (error_condition)
    {
        if (dtc->debounce_cnt < DEBOUNCE_THRESHOLD) 
        {
            dtc->debounce_cnt++;
        }
        
        if (dtc->qualifying_status == DEM_STATUS_OK) 
        {
            dtc->qualifying_status = DEM_STATUS_PENDING;
        }
        
        if (dtc->qualifying_status == DEM_STATUS_PENDING && dtc->debounce_cnt >= DEBOUNCE_THRESHOLD)
        {
            dtc->qualifying_status = DEM_STATUS_CONFIRMED;
            dtc->fault_status = DTC_STATUS_ACTIVE;
            dtc->freeze_frame_data = *(dtc->adc_source_ptr);
        }
    }
    else
    {
        if (dtc->debounce_cnt > 0) 
        {
            dtc->debounce_cnt--; 
        }
        else 
        {
            if (dtc->qualifying_status == DEM_STATUS_CONFIRMED)
            {
                dtc->qualifying_status = DEM_STATUS_OK;
                dtc->fault_status = DTC_STATUS_PASSIVE; 
            }
            else if (dtc->qualifying_status == DEM_STATUS_PENDING)
            {
                dtc->qualifying_status = DEM_STATUS_OK;
            }
        }
    }
}

void DemSf_MainFunction(void) 
{
    for (uint8_t i = 0; i < TOTAL_DTCS; i++) 
    {
        uint8_t error_detected = 0;
        
        if (g_dtc_table[i].monitor_func != NULL)
        {
            error_detected = g_dtc_table[i].monitor_func(*(g_dtc_table[i].adc_source_ptr), g_dtc_table[i].error_mode);
        }
        
        Dem_UpdateEvent(&g_dtc_table[i], error_detected);
    }
}

/* ================= PID Controller ================= */
volatile uint16_t g_PidCtrl_TargetSetpoint;
volatile bool g_PidCtrl_DisablePidController;

struct PID_Controller{
    float Kp;           
    float Ki;           
    float Kd;           
    float prev_error;   
    float integrator;   
    float out_min;      
    float out_max;      
    float deadzone;     
};

PID_Controller g_PidCtrl_PIDConverter = {
    .Kp = 0.85f,        
    .Ki = 0.15f,       
    .Kd = 0.05f,
    .prev_error = 0.0f,
    .integrator = 0.0f,
    .out_min = 5.0f,    
    .out_max = 98.0f,   
    .deadzone = 0.2f    
};

float PidCtrl_PIDCompute(PID_Controller *pid, float setpoint, float feedback, float dt) 
{
    float error = setpoint - feedback;

    if (error > -pid->deadzone && error < pid->deadzone) 
	{
        error = 0.0f;
    }

    float p_term = pid->Kp * error;

    pid->integrator += (pid->Ki * error * dt);
    if (pid->integrator > pid->out_max) pid->integrator = pid->out_max;
    if (pid->integrator < pid->out_min) pid->integrator = pid->out_min;

    float d_term = 0.0f;
    if (dt > 0.0f) 
	{
        d_term = pid->Kd * (error - pid->prev_error) / dt;
    }
    pid->prev_error = error;

    float output = p_term + pid->integrator + d_term;
    if (output > pid->out_max) output = pid->out_max;
    if (output < pid->out_min) output = pid->out_min;

    return output;
}

/* ================= COMMUNICATION DIAGNOSTICS ================= */

static uint8_t s_alive_counter_DiagFrame_ConvMonitorData = 0;
void Send_DiagFrame_ConvMonitorData(void)
{
    uint8_t checksum = 0;
    
    Uart_TxByte(0xAA);
    checksum += 0xAA;
    
    for (uint8_t i = 0; i < ADC_NUM_CH; i++)
    {
        uint16_t val = g_adc_raw[i];
        uint8_t low_byte = (uint8_t)(val & 0xFF);
        uint8_t high_byte = (uint8_t)((val >> 8) & 0xFF);
        
        Uart_TxByte(low_byte);  checksum += low_byte;
        Uart_TxByte(high_byte); checksum += high_byte;
    }
    
	Uart_TxByte(s_alive_counter_DiagFrame_ConvMonitorData); 
	checksum += s_alive_counter_DiagFrame_ConvMonitorData;

    Uart_TxByte(checksum);
    Uart_TxByte(0x0D); 

    s_alive_counter_DiagFrame_ConvMonitorData = (s_alive_counter_DiagFrame_ConvMonitorData + 1) % 16;
}

static uint8_t s_alive_counter_DiagFrame_PWMInfo = 0;
void Send_DiagFrame_PWMInfo(void)
{
    uint8_t checksum = 0;
    uint8_t bridge_status = 0; 
    
    uint16_t ocr1a_val = OCR1A;
    uint16_t ocr1b_val = OCR1B;
    uint16_t top_val   = ICR1;

    uint16_t pwm_frequency_hz = 16000000UL / (1 * (1 + top_val)); 

    if ((ocr1a_val >= (uint16_t)(top_val * 0.99f)) ||(ocr1b_val >= (uint16_t)(top_val * 0.99f)) )      { bridge_status = 1; } 
    else if (ocr1a_val <= (uint16_t)(top_val * 0.05f) || ocr1b_val <= (uint16_t)(top_val * 0.05f))     { bridge_status = 2; } 
    else                                                                                               { bridge_status = 0; }

    Uart_TxByte(0xA2); checksum += 0xA2;
    
    uint8_t ocr1a_low = (uint8_t)(ocr1a_val & 0xFF);
    uint8_t ocr1a_high = (uint8_t)((ocr1a_val >> 8) & 0xFF);
    Uart_TxByte(ocr1a_low);  checksum += ocr1a_low;
    Uart_TxByte(ocr1a_high); checksum += ocr1a_high;

    uint8_t ocr1b_low = (uint8_t)(ocr1b_val & 0xFF);
    uint8_t ocr1b_high = (uint8_t)((ocr1b_val >> 8) & 0xFF);
    Uart_TxByte(ocr1b_low);  checksum += ocr1b_low;
    Uart_TxByte(ocr1b_high); checksum += ocr1b_high;

    Uart_TxByte(bridge_status); checksum += bridge_status;

    uint8_t freq_low = (uint8_t)(pwm_frequency_hz & 0xFF);
    uint8_t freq_high = (uint8_t)((pwm_frequency_hz >> 8) & 0xFF);
    Uart_TxByte(freq_low);  checksum += freq_low;
    Uart_TxByte(freq_high); checksum += freq_high;

    Uart_TxByte(0x00); checksum += 0x00;
    
	Uart_TxByte(s_alive_counter_DiagFrame_PWMInfo); 
	checksum += s_alive_counter_DiagFrame_PWMInfo;
    Uart_TxByte(checksum);
    Uart_TxByte(0x0D); 

    s_alive_counter_DiagFrame_PWMInfo = (s_alive_counter_DiagFrame_PWMInfo + 1) % 16;
}

volatile uint8_t g_converter_state = 0;      
volatile float g_last_pid_output = 0.0f;     

static uint8_t s_alive_counter_DiagFrame_PID = 0;
void Send_DiagFrame_PIDInfo(void)
{
    uint8_t checksum = 0;
    
    Uart_TxByte(0xA3); checksum += 0xA3;
    
    uint8_t sp_high = (uint8_t)((g_PidCtrl_TargetSetpoint >> 8) & 0xFF);
    uint8_t sp_low  = (uint8_t)(g_PidCtrl_TargetSetpoint & 0xFF);
    Uart_TxByte(sp_low);   checksum += sp_low;
    Uart_TxByte(sp_high);  checksum += sp_high;

    uint16_t pid_out_raw = (uint16_t)(g_last_pid_output * 10.0f);
    uint8_t out_low = (uint8_t)(pid_out_raw & 0xFF);
    uint8_t out_high = (uint8_t)((pid_out_raw >> 8) & 0xFF);
    Uart_TxByte(out_low);  checksum += out_low;
    Uart_TxByte(out_high); checksum += out_high;

    Uart_TxByte(g_converter_state); checksum += g_converter_state;

    for (uint8_t i = 0; i < 3; i++) {
        Uart_TxByte(0x00);
        checksum += 0x00;
    }
    
    Uart_TxByte(s_alive_counter_DiagFrame_PID); 
    checksum += s_alive_counter_DiagFrame_PID;
    
    Uart_TxByte(checksum);
    Uart_TxByte(0x0D); 

    s_alive_counter_DiagFrame_PID = (s_alive_counter_DiagFrame_PID + 1) % 16;
}

volatile uint8_t g_relay_input_state = 0;  
volatile uint8_t g_relay_output_state = 0; 
static uint8_t s_alive_counter_DiagFrame_Act = 0;
void Send_DiagFrame_ActuatorInfo(void)
{
    uint8_t checksum = 0;
    
    Uart_TxByte(0xA4); checksum += 0xA4;

    Uart_TxByte(g_relay_input_state); checksum += g_relay_input_state;
    Uart_TxByte(g_relay_output_state); checksum += g_relay_output_state;

    for (uint8_t i = 0; i < 6; i++) 
	{
        Uart_TxByte(0x00);
        checksum += 0x00;
    }
    
    Uart_TxByte(s_alive_counter_DiagFrame_Act); 
    checksum += s_alive_counter_DiagFrame_Act;
    
    Uart_TxByte(checksum);
    Uart_TxByte(0x0D); 

    s_alive_counter_DiagFrame_Act = (s_alive_counter_DiagFrame_Act + 1) % 16;
}

static uint8_t s_alive_counter_DiagFrame_DTC = 0;
void Send_ActiveDTC_Frames(void)
{
    uint8_t active_indices[TOTAL_DTCS];
    uint8_t active_count = 0;

	for (uint8_t i = 0; i < TOTAL_DTCS; i++)
    {
        if (g_dtc_table[i].fault_status != DTC_STATUS_MISSING)
        {
            active_indices[active_count++] = i;
        }
    }

    if (active_count == 0)
    {
        uint8_t checksum = 0;
        Uart_TxByte(0xA5); checksum += 0xA5;
        
        for (uint8_t p = 0; p < 8; p++)
        {
            Uart_TxByte(0x00); 
            checksum += 0x00;
        }

        Uart_TxByte(s_alive_counter_DiagFrame_DTC); 
        checksum += s_alive_counter_DiagFrame_DTC;
        
        Uart_TxByte(checksum);
        Uart_TxByte(0x0D);

        s_alive_counter_DiagFrame_DTC = (s_alive_counter_DiagFrame_DTC + 1) % 16;
        return;
    }

    uint8_t total_frames = (active_count + 1) / 2; 

    for (uint8_t f = 0; f < total_frames; f++)
    {
        uint8_t checksum = 0;

        Uart_TxByte(0xA5); 
        checksum += 0xA5;

        for (uint8_t d = 0; d < 2; d++)
        {
            uint8_t dtc_idx_array_pos = (f * 2) + d;
            if (dtc_idx_array_pos < active_count)
            {
                uint8_t real_dtc_index = active_indices[dtc_idx_array_pos];
                uint32_t code = g_dtc_table[real_dtc_index].dtc_code;
                uint8_t status = g_dtc_table[real_dtc_index].fault_status;

                for (int8_t b = 2; b >= 0; b--)
                {
                    uint8_t byte_val = (uint8_t)((code >> (b * 8)) & 0xFF);
                    Uart_TxByte(byte_val); 
                    checksum += byte_val;
                }
                
                Uart_TxByte(status); 
                checksum += status;
            }
            else
            {
                for (uint8_t p = 0; p < 4; p++)
                {
                    Uart_TxByte(0x00); 
                    checksum += 0x00;
                }
            }
        }

        Uart_TxByte(s_alive_counter_DiagFrame_DTC); 
        checksum += s_alive_counter_DiagFrame_DTC;
        
        Uart_TxByte(checksum);
        Uart_TxByte(0x0D);

        s_alive_counter_DiagFrame_DTC = (s_alive_counter_DiagFrame_DTC + 1) % 16;
    }
}

void Send_NegativeResponse(uint8_t sid, uint8_t nrc)
{
    uint8_t checksum = 0;
    
    Uart_TxByte(0x7F); checksum += 0x7F;
    Uart_TxByte(sid); checksum += sid;
    Uart_TxByte(nrc); checksum += nrc;
    
    for (uint8_t i = 0; i < 7; i++) {
        Uart_TxByte(0x00);
        checksum += 0x00;
    }
    
    Uart_TxByte(checksum);
    Uart_TxByte(0x0D); 
}

void Send_PositiveResponse(uint8_t sid, const uint8_t *data, uint8_t data_len)
{
    uint8_t checksum = 0;
    uint8_t pos_sid = sid + 0x40; 
    uint8_t total_bytes_sent = 0;
    
    Uart_TxByte(pos_sid); 
    checksum += pos_sid;
    total_bytes_sent++;
    
    for (uint8_t i = 0; i < data_len; i++) {
        Uart_TxByte(data[i]);
        checksum += data[i];
        total_bytes_sent++;
    }
    
    while (total_bytes_sent < 10) {
        Uart_TxByte(0x00);
        checksum += 0x00;
        total_bytes_sent++;
    }
    
    Uart_TxByte(checksum);
    Uart_TxByte(0x0D); 
}

volatile uint8_t g_routine_active_pwm_boost_test = 0;
volatile uint8_t g_routine_active_pwm_buck_test = 0;
volatile uint8_t g_routine_active_pid_boost_test = 0;
volatile uint8_t g_routine_active_pid_buck_test = 0;
volatile uint8_t g_routine_active_input_relay_test = 0;
volatile uint8_t g_routine_active_output_relay_test = 0;

volatile uint32_t g_timer_input_relay_test_ms = 0;
volatile uint32_t g_timer_output_relay_test_ms = 0;

volatile uint8_t g_toggle_cyclic_conv_info_updates = TRUE;
volatile uint8_t g_toggle_cyclic_fault_mem_updates = TRUE;
volatile uint8_t g_toggle_cyclic_pwm_info_updates = TRUE;
volatile uint8_t g_toggle_cyclic_act_info_updates = TRUE;
volatile uint8_t g_toggle_cyclic_pid_info_updates = TRUE;

volatile uint16_t g_input_relay_step = 0;
volatile uint16_t g_output_relay_step = 0;

static uint32_t last_bridge_switch_ms = 0;
static uint8_t bridge_step = 0;

void Process_DiagnosticService(uint8_t *rx_frame)
{
    uint8_t sid = rx_frame[0]; 
    
    switch (sid)
    {
        case 0x14: 
			{
				for (uint8_t i = 0; i < TOTAL_DTCS; i++)
				{
					g_dtc_table[i].qualifying_status = DEM_STATUS_OK;
					g_dtc_table[i].fault_status = DTC_STATUS_MISSING;
					g_dtc_table[i].debounce_cnt = 0;
					g_dtc_table[i].freeze_frame_data = 0;
				}
				Send_ActiveDTC_Frames();
				Send_PositiveResponse(0x14, NULL, 0);
				break;
            }
		case 0x19: 
            {
                uint8_t sub_function = rx_frame[1]; 
                uint8_t status_mask  = rx_frame[2]; 

                if (sub_function == 0x02)
                {
                    uint8_t resp_data[3];
                    resp_data[0] = sub_function;
                    resp_data[1] = status_mask;
                    resp_data[2] = 0x00; 

                    Send_PositiveResponse(0x19, resp_data, 3);
                    Send_ActiveDTC_Frames();
                }
                else
                {
                    Send_NegativeResponse(sid, 0x12); 
                }
                break;
            }
        case 0x22: 
			{
				uint16_t requested_did = ((rx_frame[1] << 8) | rx_frame[2]);

				if (requested_did == 0x0100)
				{
					uint8_t resp_data[4] = { rx_frame[1], rx_frame[2], duty_a, duty_b};
					Send_PositiveResponse(0x22, resp_data, 4);
				}
				else if (requested_did == 0x0101)
				{
					uint8_t freq_high = (uint8_t)((target_frequency >> 8) & 0xFF);
					uint8_t freq_low  = (uint8_t)(target_frequency & 0xFF);

					uint8_t resp_data[4] = { rx_frame[1], rx_frame[2], freq_high, freq_low };
					Send_PositiveResponse(0x22, resp_data, 4);
				}				
				else if (requested_did == 0x0102) 
				{
					uint8_t setpoint_high = (uint8_t)((g_PidCtrl_TargetSetpoint >> 8) & 0xFF);
					uint8_t setpoint_low  = (uint8_t)(g_PidCtrl_TargetSetpoint & 0xFF);

					uint8_t resp_data[4] = { rx_frame[1], rx_frame[2], setpoint_high, setpoint_low };
					Send_PositiveResponse(0x22, resp_data, 4);
				}
				else if (requested_did == 0x0103) 
				{
					uint8_t resp_data[4] = { rx_frame[1], rx_frame[2], (uint8_t)g_PidCtrl_DisablePidController, 0x00 };
					Send_PositiveResponse(0x22, resp_data, 4);
				}
				else
				{
					Send_NegativeResponse(sid, 0x11);
				}
				break;
			}
		case 0x2E: 
			{
				uint16_t requested_did = ((rx_frame[1] << 8) | rx_frame[2]);

				if (requested_did == 0x0100)
				{
					if (g_PidCtrl_DisablePidController == TRUE)
					{
						duty_a = rx_frame[3];
						duty_b = rx_frame[4];
						uint8_t resp_data[4] = { rx_frame[1], rx_frame[2], duty_a, duty_b}; 
						Send_PositiveResponse(0x2E, resp_data, 4);
					}
					else
					{
						Send_NegativeResponse(sid, 0x22);
					}
				}
				else if (requested_did == 0x0101) 
				{
					target_frequency = ((rx_frame[3] << 8) | rx_frame[4]);
					ICR1 = (uint16_t)(16000000UL / (1UL * target_frequency) - 1);

					uint8_t ICR1_high = (uint8_t)((ICR1 >> 8) & 0xFF);
					uint8_t ICR1_low  = (uint8_t)(ICR1 & 0xFF);

					uint8_t resp_data[4] = { rx_frame[1], rx_frame[2], ICR1_high, ICR1_low};
					Send_PositiveResponse(0x2E, resp_data, 4);
				}
				else if (requested_did == 0x0102) 
				{
					g_PidCtrl_TargetSetpoint = ((rx_frame[3] << 8) | rx_frame[4]);
					uint8_t resp_data[4] = { rx_frame[1], rx_frame[2], rx_frame[3], rx_frame[4]};
					Send_PositiveResponse(0x2E, resp_data, 4);
				}
				else if (requested_did == 0x0103) 
				{
					g_PidCtrl_DisablePidController = rx_frame[3];
					uint8_t resp_data[4] = { rx_frame[1], rx_frame[2], rx_frame[3], 0x00};
					Send_PositiveResponse(0x2E, resp_data, 4);
				}
				else if (requested_did == 0x0104) 
				{
					uint8_t relay_cmd = rx_frame[3];
					if (relay_cmd == 1) 
					{
						PORTD |= (1 << PD4); 
						g_relay_input_state = 1;
					} 
					else 
					{
						PORTD &= ~(1 << PD4); 
						g_relay_input_state = 0;
					}

					uint8_t resp_data[4] = { rx_frame[1], rx_frame[2], relay_cmd, 0x00 };
					Send_PositiveResponse(0x2E, resp_data, 4);
				}
				else if (requested_did == 0x0105) 
				{
					uint8_t relay_cmd = rx_frame[3];
					if (relay_cmd == 1) 
 					{
						PORTD |= (1 << PD5); 
						g_relay_output_state = 1;
					} 
					else 
					{
						PORTD &= ~(1 << PD5); 
						g_relay_output_state = 0;
					}

					uint8_t resp_data[4] = { rx_frame[1], rx_frame[2], relay_cmd, 0x00 };
					Send_PositiveResponse(0x2E, resp_data, 4);
				}
				else if (requested_did == 0x0106) 
				{
					uint8_t activation_flag = rx_frame[3];
					g_toggle_cyclic_fault_mem_updates = (activation_flag == 1) ? TRUE : FALSE;
					uint8_t resp_data[4] = { rx_frame[1], rx_frame[2], g_toggle_cyclic_fault_mem_updates, 0x00 };
					Send_PositiveResponse(0x2E, resp_data, 4);
				}
				else if (requested_did == 0x0107) 
				{
					uint8_t activation_flag = rx_frame[3];
					g_toggle_cyclic_pid_info_updates = (activation_flag == 1) ? TRUE : FALSE;
					uint8_t resp_data[4] = { rx_frame[1], rx_frame[2], g_toggle_cyclic_pid_info_updates, 0x00 };
					Send_PositiveResponse(0x2E, resp_data, 4);
				}
				else if (requested_did == 0x0108) 
				{
					uint8_t activation_flag = rx_frame[3];
					g_toggle_cyclic_pwm_info_updates = (activation_flag == 1) ? TRUE : FALSE;
					uint8_t resp_data[4] = { rx_frame[1], rx_frame[2], g_toggle_cyclic_pwm_info_updates, 0x00 };
					Send_PositiveResponse(0x2E, resp_data, 4);
				}
				else if (requested_did == 0x0109) 
				{
					uint8_t activation_flag = rx_frame[3];
					g_toggle_cyclic_act_info_updates = (activation_flag == 1) ? TRUE : FALSE;
					uint8_t resp_data[4] = { rx_frame[1], rx_frame[2], g_toggle_cyclic_act_info_updates, 0x00 };
					Send_PositiveResponse(0x2E, resp_data, 4);
				}
				else if (requested_did == 0x0110) 
				{
					uint8_t activation_flag = rx_frame[3];
					g_toggle_cyclic_conv_info_updates = (activation_flag == 1) ? TRUE : FALSE;
					uint8_t resp_data[4] = { rx_frame[1], rx_frame[2], g_toggle_cyclic_conv_info_updates, 0x00 };
					Send_PositiveResponse(0x2E, resp_data, 4);
				}
				else
				{
					Send_NegativeResponse(0x2E, 0x31);
				}
				break;
			}
		case 0x31: 
			{
				uint8_t sub_function = rx_frame[1];
				uint16_t routine_id = ((rx_frame[2] << 8) | rx_frame[3]);
				
				if (sub_function == 0x01)
				{
					if (routine_id == 0x0201)
					{	
						if (g_PidCtrl_DisablePidController == TRUE)
						{
							g_routine_active_pwm_boost_test = 1; 
							uint8_t resp_data[3] = {sub_function, rx_frame[2], rx_frame[3]};
							Send_PositiveResponse(0x31, resp_data, 3);
						}
						else { Send_NegativeResponse(sid, 0x22); }
					}
					else if (routine_id == 0x0202)
					{
						if (g_PidCtrl_DisablePidController == TRUE)
						{
							g_routine_active_pwm_buck_test = 1; 
							uint8_t resp_data[3] = {sub_function, rx_frame[2], rx_frame[3]};
							Send_PositiveResponse(0x31, resp_data, 3);
						}
						else { Send_NegativeResponse(sid, 0x22); }
					}
					else if (routine_id == 0x0203)
					{	
						if (g_PidCtrl_DisablePidController == FALSE)
						{
							g_routine_active_pid_boost_test = 1; 
							uint8_t resp_data[3] = {sub_function, rx_frame[2], rx_frame[3]};
							Send_PositiveResponse(0x31, resp_data, 3);
						}
						else { Send_NegativeResponse(sid, 0x22); }
					}
					else if (routine_id == 0x0204)
					{
						if (g_PidCtrl_DisablePidController == FALSE)
						{
							g_routine_active_pid_buck_test = 1; 
							uint8_t resp_data[3] = {sub_function, rx_frame[2], rx_frame[3]};
							Send_PositiveResponse(0x31, resp_data, 3);
						}
						else { Send_NegativeResponse(sid, 0x22); }
					}
					else if (routine_id == 0x0205)
					{
						if (g_PidCtrl_DisablePidController == TRUE)
						{
							g_routine_active_input_relay_test = 1; 
							g_timer_input_relay_test_ms = g_tick_ms;
							uint8_t resp_data[4] = {sub_function, rx_frame[2], rx_frame[3], g_routine_active_input_relay_test};
							Send_PositiveResponse(0x31, resp_data, 4);
						}
						else { Send_NegativeResponse(sid, 0x22); }
					}
					else if (routine_id == 0x0206)
					{
						if (g_PidCtrl_DisablePidController == TRUE)
						{
							g_routine_active_output_relay_test = 1; 
							g_timer_output_relay_test_ms = g_tick_ms;
							uint8_t resp_data[4] = {sub_function, rx_frame[2], rx_frame[3], g_routine_active_output_relay_test};
							Send_PositiveResponse(0x31, resp_data, 4);
						}
						else { Send_NegativeResponse(sid, 0x22); }
					}
				}
				else if (sub_function == 0x02) 
				{
					if (rx_frame[2] == 0x02 && rx_frame[3] == 0x01) {g_routine_active_pwm_boost_test = 0;} 
					if (rx_frame[2] == 0x02 && rx_frame[3] == 0x02) {g_routine_active_pwm_buck_test = 0;}  
					if (rx_frame[2] == 0x02 && rx_frame[3] == 0x03) {g_routine_active_pid_boost_test = 0;}
					if (rx_frame[2] == 0x02 && rx_frame[3] == 0x04) {g_routine_active_pid_buck_test = 0;}
					if (rx_frame[2] == 0x02 && rx_frame[3] == 0x05) {g_routine_active_input_relay_test = 0;}
					if (rx_frame[2] == 0x02 && rx_frame[3] == 0x06) {g_routine_active_output_relay_test = 0;}

					uint8_t resp_data[3] = {sub_function, rx_frame[2], rx_frame[3]};
					Send_PositiveResponse(0x31, resp_data, 3);
				}
				else
				{
					Send_NegativeResponse(sid, 0x12); 
				}
				break;
            }
		default:
			{
				Send_NegativeResponse(sid, 0x11);
				break;
			}
    }
}

void Poll_RxParser(void)
{
	while (1)
	{
		uint16_t bytes_available;
		if (s_rx_head >= s_rx_tail) { bytes_available = s_rx_head - s_rx_tail; }
		else { bytes_available = UART_RX_BUF_SIZE - s_rx_tail + s_rx_head; }

		if (bytes_available < FRAME_SIZE) break;

		uint8_t terminator_index = (s_rx_tail + FRAME_SIZE - 1) % UART_RX_BUF_SIZE;
		if (s_rx_buf[terminator_index] == 0x0D)
		{
			uint8_t rx_frame[FRAME_SIZE];

			for (uint8_t i = 0; i < FRAME_SIZE; i++) 
			{
                rx_frame[i] = s_rx_buf[(s_rx_tail + i) % UART_RX_BUF_SIZE];
            }

			uint8_t calc_checksum = 0;
			for (uint8_t i = 0; i < 10; i++)
			{
				calc_checksum += rx_frame[i];
			}

			if (calc_checksum == rx_frame[10])
			{
				for (uint8_t i = 0; i < FRAME_SIZE; i++) 
				{
                    (void)Uart_RxByte(); 
                }
				Process_DiagnosticService(rx_frame);
			}
			else 
            {
                (void)Uart_RxByte();
            }
		}
        else 
        {
            (void)Uart_RxByte();
        }
	}
}

/* ===== Service 0x31 Routine Control ===== */

void Routine_Ctrl_0x31_PWM_Boost_Test(void)
{
	uint32_t g_tick_ms = Rte_Read_TickMs();
	if ((uint32_t)(g_tick_ms - last_bridge_switch_ms) >= 500) 
	{   
		last_bridge_switch_ms = g_tick_ms;
		
		if (bridge_step >= 9)
		{
			bridge_step = 0;
			g_routine_active_pwm_boost_test = 0; 
			uint8_t resp_data[5] = {0x02, 0x02, 0x01, g_routine_active_pwm_boost_test, bridge_step};
			Send_PositiveResponse(0x31, resp_data, 5);
			return;
		}

		bridge_step++;
	}

	switch (bridge_step)
	{
		case 0: OCR1A = (uint16_t)(ICR1 * 0.98f); OCR1B = (uint16_t)(ICR1 * 0.90f); break;
		case 1: OCR1A = (uint16_t)(ICR1 * 0.98f); OCR1B = (uint16_t)(ICR1 * 0.80f); break;
		case 2: OCR1A = (uint16_t)(ICR1 * 0.98f); OCR1B = (uint16_t)(ICR1 * 0.70f); break;
		case 3: OCR1A = (uint16_t)(ICR1 * 0.98f); OCR1B = (uint16_t)(ICR1 * 0.60f); break;
		case 4: OCR1A = (uint16_t)(ICR1 * 0.98f); OCR1B = (uint16_t)(ICR1 * 0.50f); break;
		case 5: OCR1A = (uint16_t)(ICR1 * 0.98f); OCR1B = (uint16_t)(ICR1 * 0.40f); break;
		case 6: OCR1A = (uint16_t)(ICR1 * 0.98f); OCR1B = (uint16_t)(ICR1 * 0.30f); break;
		case 7: OCR1A = (uint16_t)(ICR1 * 0.98f); OCR1B = (uint16_t)(ICR1 * 0.20f); break;
		case 8: OCR1A = (uint16_t)(ICR1 * 0.98f); OCR1B = (uint16_t)(ICR1 * 0.10f); break;
		case 9: OCR1A = (uint16_t)(ICR1 * 0.98f); OCR1B = (uint16_t)(ICR1 * 0.98f); break;
		default: bridge_step = 0; break;
	}
}

void Routine_Ctrl_0x31_PWM_Buck_Test(void)
{
	uint32_t g_tick_ms = Rte_Read_TickMs();
    if ((uint32_t)(g_tick_ms - last_bridge_switch_ms) >= 500) 
    {   
        last_bridge_switch_ms = g_tick_ms;
        
        if (bridge_step >= 9)
        {
            bridge_step = 0;
            g_routine_active_pwm_buck_test = 0; 
			uint8_t resp_data[5] = {0x02, 0x02, 0x02, g_routine_active_pwm_boost_test, bridge_step};
			Send_PositiveResponse(0x31, resp_data, 5);
            return;
        }

		bridge_step++;
    }

    switch (bridge_step)
    {
        case 0: OCR1A = (uint16_t)(ICR1 * 0.90f); OCR1B = (uint16_t)(ICR1 * 0.98f); break;
        case 1: OCR1A = (uint16_t)(ICR1 * 0.80f); OCR1B = (uint16_t)(ICR1 * 0.98f); break;
        case 2: OCR1A = (uint16_t)(ICR1 * 0.70f); OCR1B = (uint16_t)(ICR1 * 0.98f); break;
        case 3: OCR1A = (uint16_t)(ICR1 * 0.60f); OCR1B = (uint16_t)(ICR1 * 0.98f); break;
        case 4: OCR1A = (uint16_t)(ICR1 * 0.50f); OCR1B = (uint16_t)(ICR1 * 0.98f); break;
        case 5: OCR1A = (uint16_t)(ICR1 * 0.40f); OCR1B = (uint16_t)(ICR1 * 0.98f); break;
        case 6: OCR1A = (uint16_t)(ICR1 * 0.30f); OCR1B = (uint16_t)(ICR1 * 0.98f); break;
        case 7: OCR1A = (uint16_t)(ICR1 * 0.20f); OCR1B = (uint16_t)(ICR1 * 0.98f); break;
        case 8: OCR1A = (uint16_t)(ICR1 * 0.10f); OCR1B = (uint16_t)(ICR1 * 0.98f); break;
        case 9: OCR1A = (uint16_t)(ICR1 * 0.98f); OCR1B = (uint16_t)(ICR1 * 0.98f); break;
        default: bridge_step = 0; break;
    }
}

void Routine_Ctrl_0x31_PID_Boost_Test(float vin, float vout)
{
	uint32_t g_tick_ms = Rte_Read_TickMs();
	uint8_t boost_routine_pid_setpoint[10] = {2, 4, 6, 8, 10, 12, 14, 16, 18, 0};
	if ((uint32_t)(g_tick_ms - last_bridge_switch_ms) >= 500)
	{
		last_bridge_switch_ms = g_tick_ms;

		if (bridge_step >= 9)
        {
            bridge_step = 0;
            g_routine_active_pid_boost_test = 0; 
			uint8_t resp_data[5] = {0x02, 0x02, 0x03, g_routine_active_pid_boost_test, bridge_step};
			Send_PositiveResponse(0x31, resp_data, 5);
            return;
        }

		bridge_step++;
	}

    switch (bridge_step)
    {
		case 0: case 1: case 2: case 3: case 4: 
        case 5: case 6: case 7: case 8: case 9: 
			{
				OCR1A = (uint16_t)(ICR1 * 0.98f);

				g_PidCtrl_TargetSetpoint = vin + boost_routine_pid_setpoint[bridge_step];
				float pid_output_boost = PidCtrl_PIDCompute(&g_PidCtrl_PIDConverter, g_PidCtrl_TargetSetpoint, vout, 0.01f);
				g_last_pid_output = pid_output_boost;
				float computed_duty_b = 98.0f - pid_output_boost;
				
				if (computed_duty_b > 98.0f) computed_duty_b = 98.0f;
				if (computed_duty_b < 5.0f) computed_duty_b = 5.0f; 
				
				duty_b = (uint8_t)computed_duty_b;

				break;
			}
		default: bridge_step = 0; break;
    }
}

void Routine_Ctrl_0x31_PID_Buck_Test(float vin, float vout)
{
	uint32_t g_tick_ms = Rte_Read_TickMs();
	uint8_t buck_routine_pid_setpoint[10] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 0};
	if ((uint32_t)(g_tick_ms - last_bridge_switch_ms) >= 500)
	{
		last_bridge_switch_ms = g_tick_ms;

		if (bridge_step >= 9)
        {
            bridge_step = 0;
            g_routine_active_pid_buck_test = 0; 
			uint8_t resp_data[5] = {0x02, 0x02, 0x04, g_routine_active_pid_boost_test, bridge_step};
			Send_PositiveResponse(0x31, resp_data, 5);
            return;
        }

		bridge_step++;
	}

    switch (bridge_step)
    {
        case 0: case 1: case 2: case 3: case 4: 
		case 5:	case 6: case 7: case 8: case 9: 
			{
				OCR1B = (uint16_t)(ICR1 * 0.98f); 

				g_PidCtrl_TargetSetpoint = vin - buck_routine_pid_setpoint[bridge_step];
				float pid_output_buck = PidCtrl_PIDCompute(&g_PidCtrl_PIDConverter, vout, g_PidCtrl_TargetSetpoint, 0.01f);
				g_last_pid_output = pid_output_buck;
				float computed_duty_a = 98.0f - pid_output_buck;
				
				if (computed_duty_a > 98.0f) computed_duty_a = 98.0f;
				if (computed_duty_a < 5.0f) computed_duty_a = 5.0f;
				
				duty_a = (uint8_t)computed_duty_a;

				break;
			}
        default: bridge_step = 0; break;
    }
}

void Routine_Ctrl_0x31_InputRelay_Test(void)
{
	uint32_t g_tick_ms = Rte_Read_TickMs();

	if ((uint32_t)(g_tick_ms - g_timer_input_relay_test_ms) >= 500)
	{
		g_timer_input_relay_test_ms = g_tick_ms;

		if (g_input_relay_step >= 19)
        {
            g_routine_active_input_relay_test = 0; 
			PORTD &= ~(1 << PD4); 
			uint8_t resp_data[5] = {0x02, 0x02, 0x05, g_routine_active_input_relay_test, (uint8_t)g_input_relay_step};
			g_input_relay_step = 0;
			Send_PositiveResponse(0x31, resp_data, 5);
            return;
		}

		g_input_relay_step++;
	}

    switch (g_input_relay_step)
    {
		case 0: case 2: case 4: case 6: case 8: case 10: case 12: case 14: case 16: case 18:
		{
			PORTD |= (1 << PD4); 
			g_relay_input_state = 1;
			break;
		}
		case 1:	case 3: case 5: case 7: case 9: case 11: case 13: case 15: case 17: case 19:
		{
			PORTD &= ~(1 << PD4); 
			g_relay_input_state = 0;
			break;
		}
        default: g_input_relay_step = 0; break;
	}
}

void Routine_Ctrl_0x31_OutputRelay_Test(void)
{
	uint32_t g_tick_ms = Rte_Read_TickMs();

	if ((uint32_t)(g_tick_ms - g_timer_output_relay_test_ms) >= 500)
	{
		g_timer_output_relay_test_ms = g_tick_ms;

		if (g_output_relay_step >= 19)
        {
            g_routine_active_output_relay_test = 0; 
			PORTD &= ~(1 << PD5); 
			uint8_t resp_data[5] = {0x02, 0x02, 0x06, g_routine_active_output_relay_test, (uint8_t)g_output_relay_step};
			g_output_relay_step = 0;
			Send_PositiveResponse(0x31, resp_data, 5);
            return;
		}

		g_output_relay_step++;
	}

    switch (g_output_relay_step)
    {
		case 0: case 2: case 4: case 6: case 8: case 10: case 12: case 14: case 16: case 18:
		{
			PORTD |= (1 << PD5); 
			g_relay_output_state = 1;
			break;
		}
		case 1:	case 3: case 5: case 7: case 9: case 11: case 13: case 15: case 17: case 19:
		{
			PORTD &= ~(1 << PD5); 
			g_relay_output_state = 0;
			break;
		}
        default: g_output_relay_step = 0; break;
	}
}

/* =====================================================================
 * AUTOSAR SCHEDULER INFRASTRUCTURE
 * ===================================================================== */

volatile uint8_t g_flag_task_10ms  = 0;
volatile uint8_t g_flag_task_100ms = 0;
volatile uint8_t g_flag_task_500ms = 0;

#ifdef __cplusplus
extern "C" {
#endif

void Os_TimerTick_Hook(void)
{
    static uint16_t timer_10ms = 0;
    static uint16_t timer_100ms = 0;
    static uint16_t timer_500ms = 0;

    timer_10ms++;
    timer_100ms++;
    timer_500ms++;

    if (timer_10ms >= 10)   { timer_10ms = 0;   g_flag_task_10ms = 1; }
    if (timer_100ms >= 100) { timer_100ms = 0; g_flag_task_100ms = 1; }
    if (timer_500ms >= 500) { timer_500ms = 0; g_flag_task_500ms = 1; }
}

#ifdef __cplusplus
}
#endif

/* =====================================================================
 * AUTOSAR TASK DEFINITIONS
 * ===================================================================== */

/* Task 10ms: Achizitie date ADC, Calcul PID, Control Punte & Diagnoza DEM */
void App_Task_10ms(void)
{
    /* 1. Achizitie ADC si conversie */
    if (Rte_Read_AdcScanDone() == TRUE) 
    {
		uint16_t raw_iin = Rte_Read_AdcRaw_Iin();
		float raw_in_signed  = Acs712_Drv_ConvertToAmps(raw_iin);	
		(void)MovAvg_Update(&s_filt_iin, raw_in_signed);

		uint16_t raw_vin = Rte_Read_AdcRaw_Vin();
		V_in = Vdiv_Drv_ReadVoltage(raw_vin);	

		uint16_t raw_iout = Rte_Read_AdcRaw_Iout();
		float raw_out_signed = Acs712_Drv_ConvertToAmps(raw_iout);	
		(void)MovAvg_Update(&s_filt_iout, raw_out_signed);

		uint16_t raw_vout = Rte_Read_AdcRaw_Vout();
		V_out = Vdiv_Drv_ReadVoltage(raw_vout);	
    }
    Adc_StartScan(); 

	/* 2. Verificare Stare Convertor */
	if (V_out >= (V_in - 0.3f) && V_out <= (V_in + 0.3f))
	{
		g_converter_state = 0;
	}
	else if (V_out < V_in)
	{
		g_converter_state = 1;
	}
	else if (V_out > V_in)
	{
		g_converter_state = 2;
	}

    /* 3. Diagnoza si debouncing erori DEM */
    DemSf_MainFunction();

	/* 4. Executie PID si Control Punte */
	if (!g_routine_active_pwm_boost_test && !g_routine_active_pwm_buck_test)
	{
		if (g_PidCtrl_DisablePidController == FALSE)
		{
			float current_setpoint_volts = (float)g_PidCtrl_TargetSetpoint;
		
			if (V_out < 2.0f) 
			{
				duty_a = 98;
				duty_b = 98;
				g_PidCtrl_PIDConverter.integrator = 0.0f;
				g_PidCtrl_PIDConverter.prev_error = 0.0f;
			}
			else if (current_setpoint_volts >= (V_in - 0.3f) && current_setpoint_volts <= (V_in + 0.3f))
			{
				duty_a = 98;
				duty_b = 98;
				g_PidCtrl_PIDConverter.integrator = 0.0f; 
				g_PidCtrl_PIDConverter.prev_error = 0.0f;
			}
			else if (current_setpoint_volts > V_in)
			{
				duty_a = 98; 
				float pid_output_boost = PidCtrl_PIDCompute(&g_PidCtrl_PIDConverter, current_setpoint_volts, V_out, 0.075f);
				g_last_pid_output = pid_output_boost;
				float computed_duty_b = 98.0f - pid_output_boost;
				
				if (computed_duty_b > 98.0f) computed_duty_b = 98.0f;
				if (computed_duty_b < 5.0f) computed_duty_b = 5.0f; 
				
				duty_b = (uint8_t)computed_duty_b;
			}
			else if (current_setpoint_volts < V_in)
			{
				duty_b = 98; 
				float pid_output_buck = PidCtrl_PIDCompute(&g_PidCtrl_PIDConverter, V_out, current_setpoint_volts, 0.075f);
				g_last_pid_output = pid_output_buck;
				float computed_duty_a = 98.0f - pid_output_buck;
				
				if (computed_duty_a > 98.0f) computed_duty_a = 98.0f;
				if (computed_duty_a < 5.0f) computed_duty_a = 5.0f;
				
				duty_a = (uint8_t)computed_duty_a;
			}
		}

		uint16_t current_top = ICR1;
		OCR1A = (uint16_t)(((uint32_t) current_top * duty_a) / 100);
		OCR1B = (uint16_t)(((uint32_t) current_top * duty_b) / 100); 
	}
}

/* Task 100ms: Parser UDS & Comunicare Seriala Ciclica/Asincrona */
void App_Task_100ms(void)
{
    /* 1. Parser receptie UDS */
    Poll_RxParser();

	/* 2. Transmisie cadru ciclice / asincrone prin RTE */
    if (g_toggle_cyclic_conv_info_updates == TRUE)
    {
        Send_DiagFrame_ConvMonitorData();
    }

    if (g_toggle_cyclic_pid_info_updates == TRUE)
    {
        Send_DiagFrame_PIDInfo();
    }

    if (g_toggle_cyclic_pwm_info_updates == TRUE)
    {
        Send_DiagFrame_PWMInfo();
    }

    if (g_toggle_cyclic_act_info_updates == TRUE)
    {
        Send_DiagFrame_ActuatorInfo();
    }
}

/* Task 500ms: Rutine de Test Service 0x31 & Transmisie Memorie Erori DTC */
void App_Task_500ms(void)
{
    if (g_toggle_cyclic_fault_mem_updates == TRUE) 
    {
        Send_ActiveDTC_Frames();
    }

    /* Rutine 0x31 (Daca sunt active) */
    if (g_routine_active_pwm_boost_test)   Routine_Ctrl_0x31_PWM_Boost_Test();
    if (g_routine_active_pwm_buck_test)    Routine_Ctrl_0x31_PWM_Buck_Test();
    if (g_routine_active_pid_boost_test)   Routine_Ctrl_0x31_PID_Boost_Test(V_in, V_out);
    if (g_routine_active_pid_buck_test)    Routine_Ctrl_0x31_PID_Buck_Test(V_in, V_out);
    if (g_routine_active_input_relay_test) Routine_Ctrl_0x31_InputRelay_Test();
    if (g_routine_active_output_relay_test)Routine_Ctrl_0x31_OutputRelay_Test();
}

/* =====================================================================
 * MAIN - EXECU?IE BAZATA PE SCHEDULER AUTOSAR
 * ===================================================================== */

int main(void)
{
	/* OC1A = PB1 (D9), OC1B = PB2 (D10) */
	DDRB |= (1 << PB1) | (1 << PB2);

	uint16_t top = (uint16_t)(16000000UL / (1UL * target_frequency) - 1);
	ICR1 = top;

	/* Fast PWM, TOP = ICR1 (mode 14), non-inverting on both channels, no prescale */
	TCCR1A = (1 << COM1A1) | (1 << COM1B1) | (1 << WGM11);
	TCCR1B = (1 << WGM13) | (1 << WGM12) | (1 << CS10);

	DDRD |= (1 << PD4) | (1 << PD5); 
	// PORTD &= ~((1 << PD4) | (1 << PD5)); // Default OFF
	PORTD |= (1 << PD4) | (1 << PD5);  // Default ON
	g_relay_input_state = 1;
	g_relay_output_state = 1;

	OCR1A = (uint16_t)(top * 0.98f);   
	OCR1B = (uint16_t)(top * 0.98f);  

	ICR1_prev_val = 0;
	OCR1A_prev_val = 0;
	OCR1B_prev_val = 0;
	
	g_PidCtrl_DisablePidController = FALSE;
	g_PidCtrl_TargetSetpoint = 12;

	Adc_Init();
    Timer0_TickInit();
	Uart_Init(57600);  
    sei();

	Send_DiagFrame_PIDInfo();
	Send_DiagFrame_ActuatorInfo();
	Send_DiagFrame_PWMInfo();
    Send_ActiveDTC_Frames();

	while (1) 
	{
		/* Scheduler Dispatcher */
        if (g_flag_task_10ms) 
        {
            g_flag_task_10ms = 0;
            App_Task_10ms();
        }

        if (g_flag_task_100ms) 
        {
            g_flag_task_100ms = 0;
            App_Task_100ms();
        }

        if (g_flag_task_500ms) 
        {
            g_flag_task_500ms = 0;
            App_Task_500ms();
        }
    }
}